---
- name: Reload initd
  ansible.builtin.command: initctl reload-configuration
  changed_when: false

- name: Restart kafka service
  ansible.builtin.service:
    name: kafka
    state: restarted
  when: kafka_restart

- name: Restart kafka systemd
  ansible.builtin.systemd:
    name: kafka
    state: restarted
    daemon_reload: true
  when: kafka_restart

- name: Restart kafka-connect-standalone systemd
  ansible.builtin.systemd:
    name: kafka-connect-standalone
    state: restarted
    daemon_reload: true
  when: kafka_restart
